baseURL = "/"
googleAnalytics = "UA-XXXXXXX-Y"
languageCode = "en"
theme = "hugo-devresume-theme"
title = ""
[params]
author = "OneResume"
description = "Lane Carr"
primaryColor = "#54B689"
textPrimaryColor = "#292929"
[params.awards]
enable = false
[[params.awards.list]]
body = "Microsoft lorem ipsum"
date = "2019"
name = "Award Lorem Ipsum"
[[params.awards.list]]
body = "Oracle Aenean"
date = "2017"
name = "Award Donec Sodales"
[params.contact]
enable = true
location = "Sevierville, TN"
[[params.contact.list]]
icon = "fas fa-phone-square"
text = "(865) 771-3326"
url = "tel:(865) 771-3326"
[[params.contact.list]]
icon = "fas fa-envelope-square"
text = "lanecarr21@gmail.com"
url = "mailto:lanecarr21@gmail.com"
[params.education]
enable = true
[[params.education.list]]
dates = "2018 - 2021"
degree = "B.A. ASL Language Interpretation"
university = "Maryville College"
[params.experience]
enable = true
[[params.experience.list]]
company = "Dick's Last Resort"
dates = "2019 - Present"
details = ""
title = "Server & Bartender"
[[params.experience.list.items]]
details = "Applied positive upselling and customer service skills to ensure a satisfactory dining experience for guests according to Dick’s playful and entertaining dining model."
[[params.experience.list.items]]
details = "Prepared beverages and served meals to guests in a timely manner."
[[params.experience.list.items]]
details = "Cleaned and reset tables for new guests."
[[params.experience.list]]
company = "Converse"
dates = "2018 - Present"
details = ""
title = "Cashier"
[[params.experience.list.items]]
details = "Applied positive upselling and customer service skills to help customers locate merchandise and engage with different product options."
[[params.experience.list.items]]
details = "Maximized customer satisfaction by assisting customers with completing purchases and signing up for rewards programs."
[[params.experience.list]]
company = "WonderWorks"
dates = "2018 - 2019"
details = ""
title = "Ropes Course Attendant"
[[params.experience.list.items]]
details = "Trained all guests and new employees on safe rules and procedures for the course."
[[params.experience.list.items]]
details = "Ensured participants followed all safety protocols."
[[params.experience.list.items]]
details = "Demonstrated leadership and empathy skills by helping children and adults off the course if they were injured or scared."
[params.information]
enable = false
[[params.information.list]]
title = "Papers"
[[params.information.list.items]]
details = "2018 · Lorem Ipsum"
[[params.information.list.items]]
details = "2016 · Sed Fringilla"
[[params.information.list]]
details = "Climbing, Snowboarding, Photography, Travelling"
title = "Interests"
[params.interests]
enable = false
[[params.interests.list]]
name = "Climbing"
[[params.interests.list]]
name = "Snowboarding"
[[params.interests.list]]
name = "Photography"
[[params.interests.list]]
name = "Travelling"
[params.languages]
enable = true
[[params.languages.list]]
level = "Native"
name = "English"
[[params.languages.list]]
level = "Fluent"
name = "American Sign Language"
[params.profile]
avatar = "avatar.png"
enable = true
name = "Lane Carr"
tagline = ""
[params.projects]
enable = true
[[params.projects.list]]
meta = "President"
tagline = "•  Coordinated meetings, activities, and community outreach for the club’s participation.\n•  Kept routine contact with club members and promoted the club’s activities on campus.\n•  Increased the Sign Language Club’s average active participation by Maryville College students.\n"
title = "Sigma Lambda Kappa"
[params.skills]
enable = true
[[params.skills.list]]
title = "Technical"
[[params.skills.list.items]]
details = "CPR & First Aid"
[[params.skills.list.items]]
details = "Fluent in ASL"
[[params.skills.list]]
title = "Professional"
[[params.skills.list.items]]
details = "Effective communication"
[[params.skills.list.items]]
details = "Strong Time Management"
[[params.skills.list.items]]
details = "Creative Problem Solving"
[[params.skills.list.items]]
details = "Steady Crisis Management"
[params.social]
enable = false
[[params.social.list]]
icon = "fab fa-github-square"
title = "username"
url = "//github.com/username"
[[params.social.list]]
icon = "fab fa-linkedin"
title = "username"
url = "//linkedin.com/in/username"
[[params.social.list]]
icon = "fab fa-twitter-square"
title = "@username"
url = "//twitter.com/username"
[params.summary]
enable = false
text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."
